services:
  php:
    build:
      context: ./app/back
      dockerfile: Dockerfile # Assurez-vous que ce chemin est correct
    volumes:
      - ./app/back:/var/www/app/symfony
    working_dir: /var/www/app/symfony
    depends_on:
      - db
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/health']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  node:
    build:
      context: ./app/front
      dockerfile: Dockerfile.node # Chemin vers le nouveau Dockerfile.node
    volumes:
      - ./app/front:/var/www/react # Montez le répertoire local dans le conteneur
    working_dir: /var/www/react # Assurez-vous que le répertoire de travail est correct
    ports:
      - '5173:5173'
    command: ['npm', 'run', 'dev']
    environment:
      - VITE_SERVER_HOST=0.0.0.0 # Permet d'écouter toutes les connexions
    depends_on:
      - php # Assure que Symfony démarre avant Vite
    networks:
      - symfony-vite-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

networks:
  symfony-vite-network:
    driver: bridge

volumes:
  db_data:
