services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.dev.acme.tlschallenge=true
      - --certificatesresolvers.dev.acme.email=your@email.com
      - --certificatesresolvers.dev.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080" # dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - symfony-vite-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  php:
    image: thecodingmachine/php:8.3-v4-apache-node22
    volumes:
      - ./app/back:/var/www/html
    working_dir: /var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project.rule=Host(`${DOMAIN_NAME:-default}.localhost`)"
      - "traefik.http.routers.project.entrypoints=websecure"
      - "traefik.http.routers.project.tls=true"
      - "traefik.http.routers.project.tls.certresolver=dev"
      - "traefik.http.services.project.loadbalancer.server.port=80"
    networks:
      - symfony-vite-network

  node:
    build:
      context: ./app/front
      dockerfile: Dockerfile.node
    volumes:
      - ./app/front:/var/www/react
    working_dir: /var/www/react
    ports:
      - '5173:5173'
    command: ['npm', 'run', 'dev']
    environment:
      - VITE_SERVER_HOST=0.0.0.0
      - no_proxy=php,localhost,127.0.0.1
    depends_on:
      - php
    networks:
      - symfony-vite-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - symfony-vite-network
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-u', 'root', '-p${MYSQL_ROOT_PASSWORD}']
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: password
      UPLOAD_LIMIT: "300000000000"
    ports:
      - '${PMADB_PORT:-8080}:80'
    networks:
      - symfony-vite-network
    volumes:
      - ./config/apache/phpmyadmin.conf:/etc/apache2/conf-enabled/phpmyadmin.conf
    labels:
      - "com.docker.compose.project: '${DOMAIN_NAME:-default}"
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAIN_NAME:-default}.localhost`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

networks:
  symfony-vite-network:
    driver: bridge

volumes:
  db_data:
