nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    max_age: 3600
    allow_credentials: true
  paths:
    '^/api/': # Applique les règles CORS pour toutes les routes API
      allow_origin:
        - '%env(CORS_ALLOW_ORIGIN)%'
      allow_headers:
        - 'Content-Type'
        - 'Authorization'
      allow_methods:
        - 'POST'
        - 'GET'
        - 'OPTIONS'
      max_age: 3600
      allow_credentials: true
