# Utiliser une image Node.js officielle
FROM node:18

# Définir le répertoire de travail
WORKDIR /var/www/react

# Copier les fichiers package.json et package-lock.json (si disponible)
COPY package*.json ./

# Installer les dépendances avec npm (utilise --legacy-peer-deps si nécessaire)
RUN npm install --legacy-peer-deps

# Copier le reste du code source
COPY . .

# Commande pour démarrer l'application
CMD ["npm", "run", "dev"]
