name: Back-end Checks

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      APP_DEBUG: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Copy .env.example
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Fix PHP Code Style
        run: vendor/bin/phpcbf --standard=PSR12 src/ || true

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 src/

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.dist.neon --no-progress
