name: CI Workflow

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  docker-build:
    name: 🐳 Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

  setup-backend:
    name: 📥 Install Backend Dependencies
    runs-on: ubuntu-latest
    needs: docker-build
    env:
      APP_ENV: test
      APP_DEBUG: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2
          coverage: none

      - name: Cache Composer Packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: app/back/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('app/back/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Copy .env.example
        run: cp .env.example .env
        working-directory: app/back

      - name: Install Backend Dependencies
        run: composer install --no-cache --prefer-dist --no-progress --no-interaction
        working-directory: app/back

  setup-frontend:
    name: 📥 Install Frontend Dependencies
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: app/front

      - name: Install Frontend Dependencies
        run: npm install --no-cache
        working-directory: app/front

  backend-code-quality:
    name: 🎨 Backend Code Quality
    runs-on: ubuntu-latest
    needs: setup-backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Composer Cache
        uses: actions/cache@v3
        with:
          path: app/back/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('app/back/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Fix PHP Code Style
        run: vendor/bin/phpcbf --standard=PSR12 src/
        working-directory: app/back # ✅ Définit le bon dossier

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 src/
        working-directory: app/back # ✅ Définit le bon dossier

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.dist.neon --no-progress
        working-directory: app/back # ✅ Définit le bon dossier

  backend-tests:
    name: 🧪 Backend Tests
    runs-on: ubuntu-latest
    needs: [setup-backend, backend-code-quality]  # Ajout de la dépendance à backend-code-quality
    env:
      APP_ENV: test
      APP_DEBUG: 1
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test_db?serverVersion=15&charset=utf8"

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2
        coverage: xdebug
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Copy .env.example
      run: cp .env.example .env
      working-directory: app/back
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      working-directory: app/back

    - name: Create test database
      working-directory: app/back
      run: php bin/console doctrine:database:create --env=test

    - name: Run Unit Tests
      run: vendor/bin/phpunit --testsuite Unit --coverage-text --coverage-clover=coverage.xml
      working-directory: app/back

    - name: Run Integration Tests
      run: vendor/bin/phpunit --testsuite Integration --coverage-text --coverage-clover=coverage.xml
      working-directory: app/back

    - name: Run Functional Tests
      run: vendor/bin/phpunit --testsuite Functional --coverage-text --coverage-clover=coverage.xml
      working-directory: app/back

    - name: Cleanup test database
      if: always()
      run: php bin/console doctrine:database:drop --force --env=test --if-exists
      working-directory: app/back

  frontend-code-quality:
    name: 🎨 Frontend Code Quality
    runs-on: ubuntu-latest
    needs: setup-frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Node Modules Cache
        uses: actions/cache@v3
        with:
          path: app/front/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('app/front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check if node_modules is restored
        run: |
          echo "Listing node_modules directory"
          ls -l app/front/node_modules || echo "node_modules not found"

      - name: Install Frontend Dependencies (if not cached)
        run: npm install --no-cache
        working-directory: app/front

      - name: Run ESLint Check
        run: npm run lint
        working-directory: app/front

  frontend-build:
    name: 🏗️ Build Frontend
    runs-on: ubuntu-latest
    needs: [frontend-code-quality, backend-tests]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Node Modules Cache
        uses: actions/cache@v3
        with:
          path: app/front/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('app/front/package-lock.json') }}

      - name: Build Frontend
        run: npm run build
        working-directory: app/front # ✅ Définit le bon dossier
